// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function Make(Messages) {
  var publish = function (exchange, obj, options) {
    return exchange.publish(Curry._1(Messages[/* publisherMsgToValidJson */0], obj), options);
  };
  var consumer = function (queue) {
    return /* Task */[(function (param, res) {
                queue.consume((function (obj, acc) {
                        return Curry._1(res, /* tuple */[
                                    Curry._1(Messages[/* publisherMsgFromValidJson */1], obj),
                                    acc
                                  ]);
                      }));
                return /* NoCancel */0;
              })];
  };
  var Queue = /* module */[/* consumer */consumer];
  return /* module */[
          /* publish */publish,
          /* Queue */Queue
        ];
}

exports.Make = Make;
/* No side effect */
